
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqgwedjtczrtqdatlqgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxZ3dlZGp0Y3pydHFkYXRscWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzNjg3NjAsImV4cCI6MjA1MDk0NDc2MH0.bN9-uPgAkz2Zc6Y4Czo0QuXV5j4j1jSfT3KlDLpHako";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to call edge functions
export const callEdgeFunction = async <T>(
  functionName: string, 
  payload?: any, 
  options?: { headers?: Record<string, string> }
): Promise<T> => {
  try {
    const { data, error } = await supabase.functions.invoke<T>(
      functionName,
      {
        body: payload,
        headers: options?.headers
      }
    );
    
    if (error) {
      console.error(`Error calling ${functionName}:`, error);
      throw error;
    }
    
    return data;
  } catch (error) {
    console.error(`Failed to call ${functionName}:`, error);
    throw error;
  }
};
